name: demo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  provider: ^6.0.4
  equatable: ^2.0.5
  version: ^3.0.2
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0
  connectivity_plus: ^3.0.2
  flutter_secure_storage: ^6.0.0
  get_it: ^7.2.0
  bot_toast: ^4.0.3
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
